### ISSUE TITLE
PHP 7 suppurt

### ISSUE THREAD

**Issue by etofi** [brablc/sitebar#15]
I tried to switch my webspace to php 7 but SiteBar stops working.
Is a update for php 7 possible?

**Comment by brablc** [comment]
There is a new branch `php7` with basic support for php7. I would need at least one evening to fix all problems. So far I have tested, that I can install SiteBar and add a link.

**Comment by brablc** [comment]
Basic functionality should work now. I need reports of what is not working.

**Comment by etofi** [comment]
Sorry but it is still not working.

`[17-Nov-2016 16:09:44 Europe/Berlin] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; SB_StopWatch has a deprecated constructor in /home/www/sitebar.XXXXX.de/inc/errorhandler.inc.php on line 93
[17-Nov-2016 16:09:44 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /home/www/sitebar.XXXXX.de/lib/Nette/Debug.php:21
Stack trace:
#0 /home/www/sitebar.XXXXX.de/inc/errorhandler.inc.php(34): require_once()
#1 /home/www/sitebar.XXXXX.de/index.php(20): require_once('/home/www/siteb...')
#2 {main}
  thrown in /home/www/sitebar.XXXXX.de/lib/Nette/Debug.php on line 21`
